/**
 * Banner
 *
 * ---------------------------------------------------------------
 *
 * Leave a note to not edit the compiled JS file
 *
 *
 * For usage docs see:
 *      https://github.com/mattstyles/grunt-banner
 */
module.exports = function(grunt) {

  grunt.config.set('usebanner', {
    jrx: {
      options: {
        banner: '// Do not edit this file. It is compiled from src/distort.jsx and will be overwritten'
      },
      files: {
       src: ['distort.jsx.js']
      }
    }
  });

};
